import { NextRequest, NextResponse } from "next/server";
import productLinks from "@/lib/product-links.json";

export const dynamic = "force-dynamic";

/**
 * /go/p/<sku>
 *
 * Short, encoding-free redirect for any product in your imported feed.
 * Looks up the prodsku in lib/product-links.json (generated by
 * scripts/build-product-links.mjs from your Fanatics CSV export) and
 * redirects straight to the full tracking link — no URL encoding required.
 *
 * Example: /go/p/203470997
 */
export async function GET(
  req: NextRequest,
  { params }: { params: { sku: string } }
) {
  const links = productLinks as Record<string, string>;
  const target = links[params.sku];

  if (!target) {
    return NextResponse.redirect(new URL("/", req.url), 302);
  }

  return NextResponse.redirect(target, 302);
}
